# Generated by Django 5.2.4 on 2025-07-09 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fichier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_fichier', models.CharField(max_length=255)),
                ('date_import', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('Importé', 'Importé'), ('En cours', 'En cours'), ('Anonymisé', 'Anonymisé'), ('Exporté', 'Exporté')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RègleAnonymisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Masquage', 'Masquage'), ('Hachage', 'Hachage'), ('Randomisation', 'Randomisation'), ('Pseudonymisation', 'Pseudonymisation'), ('Suppression', 'Suppression')], max_length=20)),
                ('parametres', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mot_de_passe_hash', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('Administrateur', 'Administrateur'), ('Agent', 'Agent'), ('Visiteur', 'Visiteur')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Données',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cle', models.CharField(max_length=255)),
                ('valeur', models.TextField()),
                ('sensible', models.BooleanField(default=False)),
                ('fichier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicanon.fichier')),
            ],
        ),
        migrations.CreateModel(
            name='Historique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_traitement', models.DateTimeField(auto_now_add=True)),
                ('partage', models.BooleanField(default=False)),
                ('fichier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicanon.fichier')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medicanon.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Métriques',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lignes_traitees', models.IntegerField()),
                ('colonnes_anonymisees', models.IntegerField()),
                ('taux_anonymisation', models.FloatField()),
                ('score_securite', models.FloatField()),
                ('historique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicanon.historique')),
            ],
        ),
        migrations.CreateModel(
            name='RapportConformité',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analyse_risques', models.TextField()),
                ('recommandations', models.TextField()),
                ('historique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicanon.historique')),
            ],
        ),
        migrations.AddField(
            model_name='fichier',
            name='utilisateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medicanon.utilisateur'),
        ),
        migrations.CreateModel(
            name='Administrateur',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('medicanon.utilisateur',),
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('medicanon.utilisateur',),
        ),
        migrations.CreateModel(
            name='Visiteur',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('medicanon.utilisateur',),
        ),
        migrations.CreateModel(
            name='DonnéesRègleAnonymisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donnees', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicanon.données')),
                ('regle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicanon.règleanonymisation')),
            ],
            options={
                'unique_together': {('donnees', 'regle')},
            },
        ),
    ]
