# Generated by Django 5.2.4 on 2025-07-11 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicanon', '0003_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
