# Generated by Django 5.2.4 on 2025-07-13 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicanon', '0004_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichier',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
