# Generated by Django 5.2.4 on 2025-07-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicanon', '0005_fichier_fichier'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichier',
            name='partage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rapportconformité',
            name='conformite',
            field=models.CharField(default='Conforme RGPD/CDP', max_length=100),
        ),
        migrations.AlterField(
            model_name='fichier',
            name='fichier',
            field=models.FileField(upload_to='fichiers/'),
        ),
        migrations.AlterField(
            model_name='fichier',
            name='statut',
            field=models.CharField(choices=[('Importé', 'Importé'), ('En cours', 'En cours'), ('Anonymisé', 'Anonymisé'), ('Exporté', 'Exporté')], default='Importé', max_length=20),
        ),
        migrations.AlterField(
            model_name='règleanonymisation',
            name='type',
            field=models.CharField(choices=[('Suppression', 'Suppression'), ('Pseudonymisation', 'Pseudonymisation'), ('Généralisation', 'Généralisation'), ('Hachage', 'Hachage')], max_length=20),
        ),
    ]
