# Generated by Django 5.2.4 on 2025-07-16 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicanon', '0006_fichier_partage_rapportconformité_conformite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historique',
            name='méthode_anonymisation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historique',
            name='statut',
            field=models.CharField(choices=[('En cours', 'En cours'), ('Terminé', 'Terminé'), ('Échoué', 'Échoué')], default='En cours', max_length=20),
        ),
    ]
