# Generated by Django 5.2.4 on 2025-07-16 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicanon', '0007_historique_méthode_anonymisation_historique_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichier',
            name='fichier_anonymise',
            field=models.FileField(blank=True, null=True, upload_to='fichiers_anonymises/'),
        ),
    ]
