# Generated by Django 5.2.4 on 2025-07-18 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicanon', '0008_fichier_fichier_anonymise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichier',
            name='fichier_anonymise',
            field=models.FileField(blank=True, help_text='Fichier après anonymisation', null=True, upload_to='fichiers_anonymises/'),
        ),
    ]
