# Generated by Django 5.2.4 on 2025-07-20 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicanon', '0009_alter_fichier_fichier_anonymise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichier',
            name='fichier_anonymise',
        ),
        migrations.AddField(
            model_name='fichier',
            name='champs_anonymises',
            field=models.TextField(blank=True, help_text='Liste des champs anonymisés'),
        ),
        migrations.AddField(
            model_name='fichier',
            name='champs_preserves',
            field=models.TextField(blank=True, help_text='Liste des champs préservés'),
        ),
        migrations.AddField(
            model_name='fichier',
            name='date_anonymisation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fichier',
            name='donnees_completes_binaire',
            field=models.BinaryField(blank=True, help_text='TOUTES les données (anonymisées + préservées) en format binaire', null=True),
        ),
        migrations.AddField(
            model_name='fichier',
            name='methodes_anonymisation',
            field=models.JSONField(default=dict, help_text='Détail des méthodes par champ'),
        ),
        migrations.AddField(
            model_name='fichier',
            name='nombre_colonnes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fichier',
            name='nombre_lignes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fichier',
            name='taille_originale',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fichier',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='fichiers/'),
        ),
    ]
