# Generated by Django 5.2.4 on 2025-07-20 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicanon', '0010_remove_fichier_fichier_anonymise_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donnéesrègleanonymisation',
            name='donnees',
        ),
        migrations.AlterUniqueTogether(
            name='donnéesrègleanonymisation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='donnéesrègleanonymisation',
            name='regle',
        ),
        migrations.DeleteModel(
            name='Données',
        ),
        migrations.DeleteModel(
            name='DonnéesRègleAnonymisation',
        ),
        migrations.DeleteModel(
            name='RègleAnonymisation',
        ),
    ]
