# Generated by Django 5.2.4 on 2025-07-20 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicanon', '0011_remove_donnéesrègleanonymisation_donnees_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='medicanon_données',
        ),
        migrations.DeleteModel(
            name='medicanon_donnéesrègleanonymisation',
        ),
        migrations.DeleteModel(
            name='medicanon_règleanonymisation',  # Si vous en avez d'autres à supprimer
        ),
    ]